### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [BioImage-Archive/bia-converter#1]
Hi @kbab ,

this is looks like a useful resource! Thanks for sharing openly! I was just wondering under which conditions one could reuse the tools and code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by kbab** [comment]
Thanks for the suggestion @haesleinhuepf . @mrmh2 wrote most of the code and has added License.

**Comment by haesleinhuepf** [comment]
Awesome, thanks!
